IF OBJECT_ID('dbo.RESERVATION') IS NOT NULL
	DROP TABLE dbo.RESERVATION
GO

IF OBJECT_ID('dbo.ROOM') IS NOT NULL
	DROP TABLE dbo.ROOM
GO

create table ROOM (
	ID int identity(1,1) primary key not null,
	NUMBER bigint not null unique,
	DESCRIPTION varchar(255) not null,
	IS_ACTIVE bit not null
)

GO

CREATE UNIQUE INDEX IX_ROOM_NUMBER ON DBO.ROOM (NUMBER)
GO

CREATE INDEX IX_IS_ACTIVE ON DBO.ROOM (IS_ACTIVE)
GO

Create table RESERVATION (
	ID bigint identity(1,1) primary key not null,
	ROOM_ID int not null,
	START_DATE Date not null,
	END_DATE Date not null,
	MAIN_GUEST_DOCUMENT varchar(30) not null,
	MAIN_GUEST_NAME varchar(100) not null,
	MAIN_GUEST_EMAIL varchar(30) not null,
	IS_CONFIRMED bit not null
)
GO

ALTER TABLE RESERVATION
ADD CONSTRAINT FK_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES dbo.ROOM(ID)
GO

CREATE INDEX IX_ROOM_ID ON DBO.RESERVATION (ROOM_ID)
GO

CREATE INDEX IX_START_DATE ON DBO.RESERVATION (START_DATE)
GO

CREATE INDEX IX_END_DATE ON DBO.RESERVATION (END_DATE)
GO

CREATE INDEX IX_IS_CONFIRMED ON DBO.RESERVATION (IS_CONFIRMED)
GO